name: Automated tests

on:
  push:
    branches:
      - allure

#permissions:
#  contents: read
#  pages: write
#  id-token: write

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'temurin'

        - name: Install Chrome
          run: sudo apt-get install google-chrome-stable

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Run clean
          run: ./gradlew test --info -D selenide.headless=true
#         continue-on-error: true
